version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak  # Use host.docker.internal to refer to your localhost
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - 9090:8080
    command:
      - start-dev 
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
